// https://www.shadertoy.com/view/3dVXDc#
/**
An implementation of tileable 3D Perlin-Worley noise for modeling volumetric clouds
inspired from the chapter Real-Time Volumetric Cloudscapes by Andrew Schneider
(Guerrilla Games). The first column is the perlin-worley noise generated by remapping
perlin noise with the lowest frequency worley fbm. The next 3 columns are worley fbms
with increasing frequencies, and are used to model the cloud shapes which are rendered
in the last column. See the common tab for all the noise functions used.
*/


/**
This tab contains all the necessary noise functions required to model a cloud shape.
*/

// Hash by David_Hoskins
#define UI0 1597334673U
#define UI1 3812015801U
#define UI2 uint2(UI0, UI1)
#define UI3 uint3(UI0, UI1, 2798796415U)
#define UIF (1.0 / float(0xffffffffU))

//https://www.cs.ubc.ca/~rbridson/docs/schechter-sca08-turbulence.pdf 整数用の簡易ハッシュ関数
uint EsgtsaOrig(uint s)
{
    s = (s ^ 2747636419u) * 2654435769;
    s = (s ^ (s >> 16)) * 2654435769u;
    s = (s ^ (s >> 16)) * 2654435769u;
    return s;
}
//元々は自然な煙のアニメーションを生成するための関数らしいが、簡易なランダム値生成にも使える
float Esgtsta(float4 v)
{
    return (EsgtsaOrig(EsgtsaOrig(EsgtsaOrig(EsgtsaOrig(uint(v.x)) + uint(v.y)) + uint(v.z)) + uint(v.w))) * 2.3283064365386962890625e-10f;
}
float3 hash33(float3 p)
{
    uint3 q = uint3(int3(p)) * UI3;
    q = (q.x ^ q.y ^ q.z) * UI3;
    //return -1.0 + 2.0 * float3(q) * UIF;
    
    float3 result= float3(
        Esgtsta(float4(p, 1.0)),
        Esgtsta(float4(p, 2.0)),
        Esgtsta(float4(p, 3.0))
    ) * 2.0f - 1.0f*float3(q) * UIF;//[-1,1]に正規化
    
    return normalize(result);

}

float remap(float x, float a, float b, float c, float d)
{
    return (((x - a) / (b - a)) * (d - c)) + c;
}



// Gradient noise by iq (modified to be tileable)
float gradient_noise(float3 x, float freq)
{
    // grid
    float3 p = floor(x);
    float3 w = frac(x);
    
    // quintic interpolant
    float3 u = w * w * w * (w * (w * 6.0 - 15.0) + 10.0);

    // gradients
    float3 ga = hash33(fmod(p + float3(0.0, 0.0, 0.0), freq));
    float3 gb = hash33(fmod(p + float3(1.0, 0.0, 0.0), freq));
    float3 gc = hash33(fmod(p + float3(0.0, 1.0, 0.0), freq));
    float3 gd = hash33(fmod(p + float3(1.0, 1.0, 0.0), freq));
    float3 ge = hash33(fmod(p + float3(0.0, 0.0, 1.0), freq));
    float3 gf = hash33(fmod(p + float3(1.0, 0.0, 1.0), freq));
    float3 gg = hash33(fmod(p + float3(0.0, 1.0, 1.0), freq));
    float3 gh = hash33(fmod(p + float3(1.0, 1.0, 1.0), freq));
    
    // projections
    float va = dot(ga, w - float3(0.0, 0.0, 0.0));
    float vb = dot(gb, w - float3(1.0, 0.0, 0.0));
    float vc = dot(gc, w - float3(0.0, 1.0, 0.0));
    float vd = dot(gd, w - float3(1.0, 1.0, 0.0));
    float ve = dot(ge, w - float3(0.0, 0.0, 1.0));
    float vf = dot(gf, w - float3(1.0, 0.0, 1.0));
    float vg = dot(gg, w - float3(0.0, 1.0, 1.0));
    float vh = dot(gh, w - float3(1.0, 1.0, 1.0));
	
    // interpolation
    return va +
           u.x * (vb - va) +
           u.y * (vc - va) +
           u.z * (ve - va) +
           u.x * u.y * (va - vb - vc + vd) +
           u.y * u.z * (va - vc - ve + vg) +
           u.z * u.x * (va - vb - ve + vf) +
           u.x * u.y * u.z * (-va + vb + vc - vd + ve - vf - vg + vh);
}

// Tileable 3D worley noise
float worley_noise(float3 uv, float freq)
{
    float3 id = floor(uv);
    float3 p = frac(uv);
    
    float min_dist = 10000.0;
    for (float x = -1.; x <= 1.; ++x)
    {
        for (float y = -1.; y <= 1.; ++y)
        {
            for (float z = -1.; z <= 1.; ++z)
            {
                float3 offset = float3(x, y, z);
                float3 h = hash33(fmod(id + offset, freq)) * 0.5 + 0.5;
                h += offset;
                float3 d = p - h;
                min_dist = min(min_dist, dot(d, d));
            }
        }
    }
    
    // inverted worley noise
    return 1.0 - min_dist;
}

// Fbm for Perlin noise based on iq's blog
float perlin_fbm(float3 p, float freq, int octaves)
{
    float g = exp2(-0.85);
    float amp = 1.0;
    float noise = 0.0;
    for (int i = 0; i < octaves; ++i)
    {
        noise += amp * gradient_noise(p * freq, freq);
        freq *= 2.0;
        amp *= g;
    }
    
    return noise;
}

// Tileable Worley fbm inspired by Andrew Schneider's Real-Time Volumetric Cloudscapes chapter in GPU Pro 7.
float worley_fbm(float3 p, float freq)
{
    return worley_noise(p * freq, freq) * 0.625 +
		worley_noise(p * freq * 2.0, freq * 2.0) * 0.25 +
		worley_noise(p * freq * 4.0, freq * 4.0) * 0.125;
}

// --- Helper: Random rotation matrix ---
float3 rotate3D(float3 p, float seed)
{
    float angle = frac(sin(seed * 12.9898) * 43758.5453) * 6.28318;
    float s = sin(angle);
    float c = cos(angle);
    return float3(
        c * p.x - s * p.y,
        s * p.x + c * p.y,
        p.z
    );
}
